### ISSUE TITLE
版本问题

### ISSUE THREAD

**Issue by hbstarjason** [custa/kubernetes-cluster#1]
请问，目前暂时只支持1.9.2吗？
kubernetes-server-linux-amd64.tar.gz
kubernetes-client-linux-amd64.tar.gz

以上2个包我用的是1.11的，发现集群也能起来，发现只有2个节点：
```
# kubectl get node
NAME           STATUS    ROLES     AGE       VERSION
172.17.0.102   Ready     <none>    16h       v1.11.0
172.17.0.103   Ready     <none>    15h       v1.11.0

**Comment by custa** [comment]
@hbstarjason 你好，笔记本的内存不够，所以只在节点1启动 master 的进程，在节点2和节点3启动 node 的进程。你需要在所有节点启动所有进程的话，可以改下这里的 if 语句。
https://github.com/custa/kubernetes-cluster/blob/master/Vagrantfile#L146-L157
